name: docs
on:
    push:
        branches:
            - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6 - 3.9'
        architecture: 'x64'
    - name: Install the library
      run: |
        pip install nbdev jupyter
        pip install -e .
        pip install mkdocs-material mkdocstrings mkdocs-jupyter

    - name: config
      run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
    - name: deploy docs 
      run: |
        mkdocs gh-deploy --force
